name: configuration du projet
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du projet
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache des dépendances
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Install dependencies
        run: mvn install

      - name: Build application
        run: mvn package

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: build_app
          path: target/*.jar
